name: Deploy to production serve
on:
  push:	
    branches:	
      - master

jobs:
  deploy:
    name: Deploy to production serve
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@master
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: npm install and build
      run: |
        npm install
        npm run build

    - name: Deploy
      uses: s0/git-publish-subdir-action@master
      env:
        REPO: git@github.com:iluminoguru/ng-ci-cd.git
        BRANCH: artifacts
        FOLDER: dist/ng-v9
        SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_PRIVATE_KEY_NEW }}
        KNOWN_HOSTS_FILE: src/known_hosts
    - name: Checkout
      uses: actions/checkout@artifacts
    - name: deploy file
      uses: wlixcc/SFTP-Deploy-Action@v1.0
      with:
        username: 'ishan'
        server: '139.59.57.41'
        private_key: ${{ secrets.DEPLOY_PRIVATE_KEY_NEW }} 
        local_path: './*'
        remote_path: '/var/www/html/app.bmi' #make sure dir exist
        args: '-o ConnectTimeout=5'
